### ISSUE TITLE
Bug on right sidebar on Firefox

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material-demo#9]
The sidebar of the right of the screen open as a weird scrolled panel on Firefox:

![screenshot from 2015-11-16 11 05 00](https://cloud.githubusercontent.com/assets/7464735/11182589/fcef8022-8c52-11e5-95fc-603f6422df03.png)

The demo already opens with that floating panel on the screen.

Tested on Firefox 42.0 on Ubuntu 14.04.2 x64.

**Comment by pedjapesic** [comment]
On mobile when you swipe screen on left, this panel will be revealed and this right panel looks funny like it was hiding there and it's suddenly found when I move everything on the left :-)

![right](https://cloud.githubusercontent.com/assets/9980558/11374515/bd9b9fa2-92d6-11e5-97ee-c4ebeba9b42f.png)

**Comment by kevzlou7979** [comment]
Ok this one is fixed, I just need to set the html tag css to overflow-x: hidden;

**Comment by pedjapesic** [comment]
In addition to previously explained I have noticed that modal dialogs on mobile are not centered correctly because of this. Even when right panel is hidden, modal dialog is taking into account right space, so dialogs are moved on the right. It's still the same error on both demo links.

**Comment by kevzlou7979** [comment]
Thanks i will take a look on it

**Comment by kevzlou7979** [comment]
Ok this was fixed on 1.5.1
